### ISSUE TITLE
accessing a map field without an assign should work

### ISSUE THREAD

**Issue by Sanegv** [Eclalang/Ecla#215]
works:
```ecla
import "console";

var arr map[int]string = {0:"zero", 1:"one", 2:"two"};
i := arr[1];

console.println(arr);
``` 

doesn't work : 

```ecla
import "console";

var arr map[int]string = {0:"zero", 1:"one", 2:"two"};
arr[1];

console.println(arr);```
`Fatal Error Line: 4, Col: 7`
`Unknown opperator" ; in variable assignement`

**Comment by mkarten** [comment]
What you are suggesting is not an error.

In ecla an indexable access of a variable is both a rValue and a lValue so you cannot access it simply by putting it at the start of a line ended by a semicolon, you need to do an operation with it like for example an assignement
The parser simply cannot determinate what you are trying to use it for

Moreover if you take the example of the functions the call cannot be used as a lValue so you can call it just by herself since the parser can deterministically know it can be used as an assignement lValue
